import bash from "highlight.js/lib/languages/bash";
import c from "highlight.js/lib/languages/c";
import cpp from "highlight.js/lib/languages/cpp";
import csharp from "highlight.js/lib/languages/csharp";
import css from "highlight.js/lib/languages/css";
import diff from "highlight.js/lib/languages/diff";
import go from "highlight.js/lib/languages/go";
import ini from "highlight.js/lib/languages/ini";
import java from "highlight.js/lib/languages/java";
import javascript from "highlight.js/lib/languages/javascript";
import json from "highlight.js/lib/languages/json";
import kotlin from "highlight.js/lib/languages/kotlin";
import less from "highlight.js/lib/languages/less";
import lua from "highlight.js/lib/languages/lua";
import makefile from "highlight.js/lib/languages/makefile";
import markdown from "highlight.js/lib/languages/markdown";
import plaintext from "highlight.js/lib/languages/plaintext";
import python from "highlight.js/lib/languages/python";
import pythonRepl from "highlight.js/lib/languages/python-repl";
import r from "highlight.js/lib/languages/r";
import rust from "highlight.js/lib/languages/rust";
import scss from "highlight.js/lib/languages/scss";
import shell from "highlight.js/lib/languages/shell";
import sql from "highlight.js/lib/languages/sql";
import swift from "highlight.js/lib/languages/swift";
import typescript from "highlight.js/lib/languages/typescript";
import xml from "highlight.js/lib/languages/xml";
import yaml from "highlight.js/lib/languages/yaml";
import { registerLanguage } from "./src/core";
registerLanguage("bash", bash);
registerLanguage("c", c);
registerLanguage("cpp", cpp);
registerLanguage("csharp", csharp);
registerLanguage("css", css);
registerLanguage("diff", diff);
registerLanguage("go", go);
registerLanguage("ini", ini);
registerLanguage("java", java);
registerLanguage("javascript", javascript);
registerLanguage("json", json);
registerLanguage("kotlin", kotlin);
registerLanguage("less", less);
registerLanguage("lua", lua);
registerLanguage("makefile", makefile);
registerLanguage("markdown", markdown);
registerLanguage("plaintext", plaintext);
registerLanguage("python", python);
registerLanguage("python-repl", pythonRepl);
registerLanguage("r", r);
registerLanguage("rust", rust);
registerLanguage("scss", scss);
registerLanguage("shell", shell);
registerLanguage("sql", sql);
registerLanguage("swift", swift);
registerLanguage("typescript", typescript);
registerLanguage("xml", xml);
registerLanguage("yaml", yaml);
